name: PHP CS Fixer checks

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@master
      - uses: ramsey/composer-install@v2

      - name: PHP CS Fixer checks
        run: |
          vendor/bin/php-cs-fixer fix -v --dry-run