name: Codeception Integration tests

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: testdb
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@master
      - uses: ramsey/composer-install@v2

      - name: Run Codeception integration tests
        run: vendor/bin/codecept run integration