name: Codeception Unit tests

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@master
      - uses: ramsey/composer-install@v2

      - name: Run Codeception unit tests
        run: vendor/bin/codecept run unit